### ISSUE TITLE
-변경사항

### ISSUE THREAD

**Issue by ThrownDice** [ThrownDice/UB#19]
1. 하나의 컨트롤러에서 여러 모델을 쓸 수 있도록 지원함에 따라, 컨트롤러가 구지 model 객체를 가지고 있어야 하나라는 생각이 듬. -> 그냥 코어 객체에서 getInstance로 여러 컨트롤러에서 하나의 model 객체를 쓸 수 있도록 하는게 어떤지 코드 작성중.
2. Term List 페이지 구현
3. Term 추가 하기 기능 구현
4. Term edit 페이지 구현 (Term edit 페이지는 request method에 따라 추가, 수정으로 사용중)
5. 기타 디자인, css 코드 추가

**Comment by eldenpark** [comment]
1. 두 가지 이유.
   a. 컨트롤러가 어떤 모델과 연동하는지 코드 내부에서 명시하는 것->개발자가 인지하기 쉽기 때문에, 개발에 용이.

b. Controller->render(). 컨트롤러에서 render()를 실행한다고 가정했을 때, render() 내부에서 $model['model'] 로 쉽게 모델 객체를 가져올 수 있다.

**Comment by ThrownDice** [comment]
0.0.2 Term CRUD 기본적인 기능들이 모두 구현됨
