### ISSUE TITLE
08.02 회의의 결과

### ISSUE THREAD

**Issue by eldenpark** [ThrownDice/UB#25]
1. getControllerParameter()
   $maps: $routes(, $route)로 함이 어떨지..
2. getInstance()
   $new_class: $instance 로 함이 어떨지..
3. equals()
   : match()로 함수 이름 변경. 내부 변수 $match -> $matched[#] 로 변경함이 어떨지..
4. View객체의 구성하여 삽입 예정.
5. 코드 내 주석: 없는 것 내가 달고, 달아놓은것 영어문법 첨삭 해도 될런지?
6. SRS, ub.xml 업데이트 예고.
7. DB생성을 위한 Query 필요.

**Comment by ThrownDice** [comment]
1,2,3 done
