### ISSUE TITLE
yet another issue after today's meeting.

### ISSUE THREAD

**Issue by eldenpark** [ThrownDice/UB#26]
1. View 객체. 
   sys/core 에 추가.
   prototype 구현 완료. (template_term_list에 대하여 test 완료 및 코드 남김)
   Controller 객체 생성 시, $view 를 param으로 받는 것 꼭 필요한 것인지? 제거 검토요망.
2. getControllerParameter 메소드명 getControllerParam 으로 줄임이 어떨지 검토요망.
3. Controller 객체에 $_info, $constant 두 가지 멤버변수 역할이 무엇이고 두 개 모두 존재해야하는지?
   논의 필요. -> 변수를 가급적 직관적이고 최소화하는 방향으로 검토 요망.
4. Controller에서 render 하는 알고리즘. 논의 필요.

**Comment by ThrownDice** [comment]
2번 done

**Comment by ThrownDice** [comment]
이슈 닫음
