### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by eldenpark** [ThrownDice/UB#28]
1. Model 객체
   : getDatabase()를 구현해 두고, Model상속 개체의 다양한 method에서 이를 이용하는 것 같은데, 
   해당 작업하지않고, Model에도 멤버변수 $db를 두어 해당 작업 이후의 결과물을 가지고 있음이 어떠한지? 해당 내용. 코드에 구현해 놓음.
2. Controller 객체
   : model객체들을 가지고 있는 변수를 삭제한 것 같은데, 지난 주말 회의에서 논의한 바와 같이, 한 controller가 model여럿을 두고 있을 시, 이를 효과적으로 제어하기 위해 model 배열변수 두는 게 어떠한지? 우선 코드에 반영해 놓음.

**Comment by ThrownDice** [comment]
일단 이슈 닫음
